# Generated by Django 3.1.7 on 2021-03-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoriaformula',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('id_formula', models.IntegerField()),
            ],
            options={
                'db_table': 'categoriaformula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(db_column='id_formula', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_latex', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('creada', models.IntegerField()),
                ('eliminada', models.IntegerField()),
            ],
            options={
                'db_table': 'formula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(db_column='id_historial', primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(db_column='id_imagen', primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'imagen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.AutoField(db_column='id_index', primary_key=True, serialize=False)),
                ('numero_usos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'indice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.AutoField(db_column='id_recomendacion', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recomendacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(db_column='id_script', primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=1000)),
                ('variables_script', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'script',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(db_column='id_tag', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tagformula',
            fields=[
                ('id_tag', models.IntegerField(primary_key=True, serialize=False)),
                ('id_formula', models.IntegerField()),
            ],
            options={
                'db_table': 'tagformula',
                'managed': False,
            },
        ),
    ]
