# Generated by Django 3.1.7 on 2021-03-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('is_active', models.IntegerField(db_column='activo', default=1, verbose_name='1: Usuario activo, 0: Usuario inactivo')),
                ('email', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField()),
                ('last_login', models.DateTimeField(auto_now_add=True, db_column='ultimo_ingreso', verbose_name='last login')),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(db_column='id_carrera', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id_usuario', models.IntegerField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('id_carrera', models.IntegerField(db_column='id_carrera')),
            ],
            options={
                'db_table': 'interes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetaUser',
            fields=[
                ('nombre_usuario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('clave_encriptada', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MetaUsuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Niveleducativo',
            fields=[
                ('id', models.AutoField(db_column='id_niveleducativo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'niveleducativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
    ]
