# Generated by Django 3.1.7 on 2021-03-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mytevar',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'mytevar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pinpago',
            fields=[
                ('id', models.AutoField(db_column='id_pinpago', primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('fecha_vencimiento', models.DateField()),
                ('ref_pago', models.IntegerField()),
                ('pin', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'pinpago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetacredito',
            fields=[
                ('id', models.AutoField(db_column='id_tarjetacredito', primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('cvv', models.IntegerField(blank=True, db_column='CVV', null=True)),
            ],
            options={
                'db_table': 'tarjetacredito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuariotarjeta',
            fields=[
                ('id_tarjetacredito', models.OneToOneField(db_column='id_tarjetacredito', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.tarjetacredito')),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuariotarjeta',
                'managed': False,
            },
        ),
    ]
