# Generated by Django 3.1.7 on 2021-03-14 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUsuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('clave_encriptada', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_rol', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mauth.rol', verbose_name='Rol del usuario')),
                ('nombre_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mauth.metausuario', verbose_name='Meta información del usuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
