# Generated by Django 3.2.8 on 2021-10-20 23:58

from django.db import migrations, models
import djongo.models.fields
import maths.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_formula', models.IntegerField()),
                ('added_at', models.DateTimeField()),
                ('tags', djongo.models.fields.ArrayField(model_container=maths.models.StringObject, model_form_class=maths.models.StringObjectForm)),
                ('title', models.TextField()),
                ('latex_code', models.CharField(max_length=200)),
                ('images', djongo.models.fields.ArrayField(model_container=maths.models.Image, model_form_class=maths.models.ImageForm)),
                ('is_deleted', models.BooleanField()),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id_image', models.IntegerField()),
                ('added_at', models.DateTimeField()),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
